# Generated by Django 5.0.6 on 2026-07-18 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieFeatureCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('features', models.JSONField()),
                ('genres', models.JSONField(default=list)),
                ('actors', models.JSONField(default=list)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('keywords', models.JSONField(default=list)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('freshness_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-popularity_score'],
            },
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='watch_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='watch_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('recommendation_source', models.CharField(max_length=100)),
                ('feedback_type', models.CharField(max_length=20)),
                ('feedback_value', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_preferences', models.JSONField(default=dict)),
                ('actor_preferences', models.JSONField(default=dict)),
                ('director_preferences', models.JSONField(default=dict)),
                ('content_features', models.JSONField(default=dict)),
                ('avg_watch_time', models.FloatField(default=0.0)),
                ('avg_completion_rate', models.FloatField(default=0.0)),
                ('total_movies_watched', models.IntegerField(default=0)),
                ('total_likes_given', models.IntegerField(default=0)),
                ('total_search_queries', models.IntegerField(default=0)),
                ('preferred_hours', models.JSONField(default=list)),
                ('preferred_days', models.JSONField(default=list)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('session_count', models.IntegerField(default=0)),
                ('user_embedding', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMovieInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('movie_title', models.CharField(max_length=255)),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('search', 'Search'), ('like', 'Like'), ('watchlist', 'Watchlist'), ('share', 'Share'), ('rate', 'Rate'), ('watch_time', 'Watch Time'), ('complete', 'Complete')], max_length=20)),
                ('value', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'movie_id', 'interaction_type'], name='movies_user_user_id_510ff6_idx'), models.Index(fields=['created_at'], name='movies_user_created_9490a2_idx')],
            },
        ),
    ]
